export enum PublicMessage {
  ProductCreated = "product created successfuly !",
  Productdeleted = "product deleted successfuly !",
  ProductUpdated = "product udpated successfuly !",
  ProductDetailCreated = "product detail created successfuly !",
  ProductDetailUpdated = "product detail updated successfuly !",
  ProductDetailDeleted = "product detail deleted successfuly !",
  ProductSizeCreated = "product size created successfuly !",
  ProductSizeUpdated = "product size updated successfuly !",
  ProductSizeDeleted = "product size deleted successfuly !",
  ProductColorCreated = "product color created successfuly !",
  ProductColorUpdated = "product color updated successfuly !",
  ProductColorDeleted = "product color deleted successfuly !",
  DiscountCreated = "discount created successfuly !",
  DiscountUpdated = "discount updated successfuly !",
  DiscountDeleted = "discount deleted successfuly !",
  ProductAddedToCart = "product added to cart successfuly !",
  ProductRemovedFromCart = "product removed from cart successfuly !",
  DiscountAddedToCart = "dicount added to cart successfuly !",
  DiscountRemovedFromCart = "discount removed from cart successfuly !",
}
export enum NotFoundMessage {
  ProductNotFound = "product not found !",
  ProductDetailNotFound = "product detail not found !",
  ProductSizeNotFound = "product size not found !",
  ProductColorNotFound = "product color not found !",
  DiscountNotFound = "discount not found !",
  ProductNotFoundInCart = "product not found in cart !",
}
export enum BadRequestMessage {
  ProductTypeInvalid = "product type is invalid !",
  ProductTypeNotSizing = "this product type is not sizing !",
  ProductTypeNotColoring = "this product type is not coloring !",
  InvalidDiscountPriceType = "enter either amount or percent !",
  InvalidDiscountType = "discount type is invalid !",
  ProductIdRequired = "product id required for a discount with type product",
  ProductIdContradiction = "product id should not exist when discount type is cart !",
  ExpirationDateIsExpired = "expiration date is past, expiration date should be in future !",
  SizeIdAndColorIdContradiction = "both colorId and sizeId are not allowed !",
  ProductOutOfStock = "product is out of stock !",
  ColorIdRequired = "color id is required for a coloring product !",
  SizeIdRequired = "size id is required for a sizing product !",
  ProductColorOutOfStock = "this product color is out of stock !",
  ProductSizeOutOfStock = "this product size is out of stock !",
  ProductColorAndSizeNotAllowed = "product color or size not allowed for single product !",
  DiscountCodeLimitReached = "discount code limit reached !",
  DiscountCodeExpired = "discount code expired !",
  ForbiddenProductDiscount = "you can only use this discount when related product is in cart !",
  DiscountAlreadyInUse = "discout code is already in use !",
  DiscountUsageLimitReached = "you can only use one public discount !",
  DiscountIsNotInCart = "discount is not in cart and can not be removed !",
}

export enum ConflictMessage {
  ProductDetailAlreadyExist = "product detail with this key already exists !",
  ProductSizeAlreadyExist = "product size with this size already exists !",
  ProductColorAlreadyExist = "product color with this color already exists !",
  DiscountCodeAlreadyExist = "discount with this code is already exists !",
}
